### ISSUE TITLE
1.2 | Onderzoeksrapport maken

### ISSUE THREAD

**Issue by EHammer98** [EHammer98/Liffie#11]
Alle bevindingen van 1.1 verwerken in een document.

**Comment by EHammer98** [comment]
@Obispy deze kan toch gesloten worden??

**Comment by Obispy** [comment]
laten wij deze er maar in staan zodat we een reminder hebben dat we het nog een keer moeten nakijken

**Comment by EHammer98** [comment]
@Obispy dat is goed. Dan kijken we er nog een keer naar als we #12 gaan doen, dan kan daarna deze ook gesloten worden.

**Comment by EHammer98** [comment]
Ik ga er door heen lezen, kaart kan gesloten worden
